# Load ggplot
library(ggplot2)
# Make a copy of the data set
Multiple_Trained_Score_2copy <- Multiple_Trained_Score_2
# Convert Applicatons and Starts to a factor
Multiple_Trained_Score_2copy$A_S_Label <- factor(Multiple_Trained_Score_2copy$A_S_Label)
# Map Applications and starts to fill, make the bars NOT stacked, and make them semitransparent
# Creat values for each school
Ashford_D <- ggplot(Multiple_Trained_Score_2copy, aes(x=Ashford.Probability, fill=A_S_Label)) + geom_density(alpha=.3) + ggtitle("Ashfrod University") + labs(x="Probability", y="Density") + theme(plot.title = element_text(color="111111",  size=12, hjust=.5)) + theme(axis.title = element_text(color="#111111",  size=10)) + scale_fill_discrete(name="Application Status")
AIU_D <- ggplot(Multiple_Trained_Score_2copy, aes(x=AIU.Probability, fill=A_S_Label)) + geom_density(alpha=.3) + ggtitle("AIU University") + labs(x="Probability", y="Density") + theme(plot.title = element_text(color="#111111",  size=12, hjust=.5)) + theme(axis.title = element_text(color="#111111",  size=10)) + scale_fill_discrete(name="Application Status")
Argosy_D <- ggplot(Multiple_Trained_Score_2copy, aes(x=Argosy.Probability, fill=A_S_Label)) + geom_density(alpha=.3) + ggtitle("Argosy University") + labs(x="Probability", y="Density") + theme(plot.title = element_text(color="#111111",  size=12, hjust=.5)) + theme(axis.title = element_text(color="#111111",  size=10)) + scale_fill_discrete(name="Application Status")
CTU_D <- ggplot(Multiple_Trained_Score_2copy, aes(x=CTU.Probability, fill=A_S_Label)) + geom_density(alpha=.3) + ggtitle("CTU University") + labs(x="Probability", y="Density") + theme(plot.title = element_text(color="#111111",  size=12, hjust=.5)) + theme(axis.title = element_text(color="#111111",  size=10)) + scale_fill_discrete(name="Application Status")
Everest_D <- ggplot(Multiple_Trained_Score_2copy, aes(x=Everest.Probability, fill=A_S_Label)) + geom_density(alpha=.3) + ggtitle("Everest University") + labs(x="Probability", y="Density") + theme(plot.title = element_text(color="#111111",  size=12, hjust=.5)) + theme(axis.title = element_text(color="#111111",  size=10)) + scale_fill_discrete(name="Application Status")
NorthCentral_D <- ggplot(Multiple_Trained_Score_2copy, aes(x=NorthCentral.Prob, fill=A_S_Label)) + geom_density(alpha=.3) + ggtitle("North Central University") + labs(x="Probability", y="Density") + theme(plot.title = element_text(color="#111111",  size=12, hjust=.5)) + theme(axis.title = element_text(color="#111111",  size=10)) + scale_fill_discrete(name="Application Status")
UltimateMedical_D <- ggplot(Multiple_Trained_Score_2copy, aes(x=Ultimate.Medical.Probability, fill=A_S_Label)) + geom_density(alpha=.3) + ggtitle("Ultimate Medial University") + labs(x="Probability", y="Density") + theme(plot.title = element_text(color="#111111",  size=12, hjust=.5)) + theme(axis.title = element_text(color="#111111",  size=10)) + scale_fill_discrete(name="Application Status")
GrandCanyon_D <- ggplot(Multiple_Trained_Score_2copy, aes(x=GrandCanyon.Probability, fill=A_S_Label)) + geom_density(alpha=.3) + ggtitle("Grand Canyon University") + labs(x="Probability", y="Density") + theme(plot.title = element_text(color="#111111",  size=12, hjust=.5)) + theme(axis.title = element_text(color="#111111",  size=10)) + scale_fill_discrete(name="Application Status")
ColoradoChristian_D <- ggplot(Multiple_Trained_Score_2copy, aes(x=Col.Christian.Probability, fill=A_S_Label)) + geom_density(alpha=.3) + ggtitle("Colorado Christian University") + labs(x="Probability", y="Density") + theme(plot.title = element_text(color="#111111",  size=12, hjust=.5)) + theme(axis.title = element_text(color="#111111",  size=10)) + scale_fill_discrete(name="Application Status")
South_D <- ggplot(Multiple_Trained_Score_2copy, aes(x=South.Probability, fill=A_S_Label))+ geom_density(alpha=.3) + ggtitle("South University") + labs(x="Probability", y="Density") + theme(plot.title = element_text(color="#111111",  size=12, hjust=.5)) + theme(axis.title = element_text(color="#111111",  size=10)) + scale_fill_discrete(name="Application Status")
Ashford_H <- ggplot(Multiple_Trained_Score_2copy, aes(x=Ashford.Probability, fill=A_S_Label)) + geom_histogram(position="identity", alpha=0.4, bins = 100) + scale_y_log10() + ggtitle("Ashfrod University") + labs(x="Probability", y="Total Count") + theme(plot.title = element_text(color="#111111",  size=12, hjust=.5)) + theme(axis.title = element_text(color="#111111",  size=10)) + scale_fill_discrete(name="Application Status")
AIU_H <- ggplot(Multiple_Trained_Score_2copy, aes(x=AIU.Probability, fill=A_S_Label)) + geom_histogram(position="identity", alpha=0.4, bins = 100) + scale_y_log10() + ggtitle("AIU University") + labs(x="Probability", y="Total Count") + theme(plot.title = element_text(color="#111111",  size=12, hjust=.5)) + theme(axis.title = element_text(color="#111111",  size=10)) + scale_fill_discrete(name="Application Status")
Argosy_H <- ggplot(Multiple_Trained_Score_2copy, aes(x=Argosy.Probability, fill=A_S_Label)) + geom_histogram(position="identity", alpha=0.4, bins = 100) + scale_y_log10() + ggtitle("Argosy University") + labs(x="Probability", y="Total Count") + theme(plot.title = element_text(color="#111111",  size=12, hjust=.5)) + theme(axis.title = element_text(color="#111111",  size=10)) + scale_fill_discrete(name="Application Status")
CTU_H <- ggplot(Multiple_Trained_Score_2copy, aes(x=CTU.Probability, fill=A_S_Label)) + geom_histogram(position="identity", alpha=0.4, bins = 100) + scale_y_log10() + ggtitle("CTU") + labs(x="Probability", y="Total Count") + theme(plot.title = element_text(color="#111111",  size=12, hjust=.5)) + theme(axis.title = element_text(color="#111111",  size=10)) + scale_fill_discrete(name="Application Status")
Everest_H <- ggplot(Multiple_Trained_Score_2copy, aes(x=Everest.Probability, fill=A_S_Label)) + geom_histogram(position="identity", alpha=0.4, bins = 100) + scale_y_log10() + ggtitle("Everest University") + labs(x="Probability", y="Total Count") + theme(plot.title = element_text(color="#111111",  size=12, hjust=.5)) + theme(axis.title = element_text(color="#111111",  size=10)) + scale_fill_discrete(name="Application Status")
NorthCentral_H <- ggplot(Multiple_Trained_Score_2copy, aes(x=NorthCentral.Prob, fill=A_S_Label)) + geom_histogram(position="identity", alpha=0.4, bins = 100) + scale_y_log10() + ggtitle("North Central University") + labs(x="Probability", y="Total Count") + theme(plot.title = element_text(color="#111111",  size=12, hjust=.5)) + theme(axis.title = element_text(color="#111111",  size=10)) + scale_fill_discrete(name="Application Status")
UltimateMedical_H <- ggplot(Multiple_Trained_Score_2copy, aes(x=Ultimate.Medical.Probability, fill=A_S_Label)) + geom_histogram(position="identity", alpha=0.4, bins = 100) + scale_y_log10() + ggtitle("Ultimate Medial") + labs(x="Probability", y="Total Count") + theme(plot.title = element_text(color="#111111",  size=12, hjust=.5)) + theme(axis.title = element_text(color="#111111",  size=10)) + scale_fill_discrete(name="Application Status")
GrandCanyon_H <- ggplot(Multiple_Trained_Score_2copy, aes(x=GrandCanyon.Probability, fill=A_S_Label)) + geom_histogram(position="identity", alpha=0.4, bins = 100) + scale_y_log10() + ggtitle("Grand Canyon University") + labs(x="Probability", y="Total Count") + theme(plot.title = element_text(color="#111111",  size=12, hjust=.5)) + theme(axis.title = element_text(color="#111111",  size=10)) + scale_fill_discrete(name="Application Status")
ColoradoChristian_H <- ggplot(Multiple_Trained_Score_2copy, aes(x=Col.Christian.Probability, fill=A_S_Label)) + geom_histogram(position="identity", alpha=0.4, bins = 100) + scale_y_log10() + ggtitle("Colorado Christian University") + labs(x="Probability", y="Total Count") + theme(plot.title = element_text(color="#111111",  size=12, hjust=.5)) + theme(axis.title = element_text(color="#111111",  size=10)) + scale_fill_discrete(name="Application Status")
South_H <- ggplot(Multiple_Trained_Score_2copy, aes(x=South.Probability, fill=A_S_Label)) + geom_histogram(position="identity", alpha=0.4, bins = 100) + scale_y_log10() + ggtitle("South University") + labs(x="Probability", y="Total Count") + theme(plot.title = element_text(color="#111111",  size=12, hjust=.5)) + theme(axis.title = element_text(color="#111111",  size=10)) + scale_fill_discrete(name="Application Status")
###
###
require(gridExtra)
grid.arrange(Ashford_D, Ashford_H, AIU_D, AIU_H, Argosy_D, Argosy_H, CTU_D, CTU_H, NorthCentral_D, NorthCentral_H, ColoradoChristian_D, ColoradoChristian_H, Everest_D, Everest_H, GrandCanyon_D, GrandCanyon_H, South_D, South_H, UltimateMedical_D, UltimateMedical_H, ncol=4)
