# Make a copy of the data set
Multiple_Trained_Score_2copy <- Multiple_Trained_Score_2
# Convert Applicatons and Starts to a factor
Multiple_Trained_Score_2copy$A_S_Label <- factor(Multiple_Trained_Score_2copy$A_S_Label)
# Map Applications and starts to fill, make the bars NOT stacked, and make them semitransparent
# Creat values for each school
Ashford_H <- ggplot(Multiple_Trained_Score_2copy, aes(x=Ashford.Probability, fill=A_S_Label)) + geom_histogram(position="identity", alpha=0.4, bins = 100) + scale_y_log10() + ggtitle("Ashfrod University") + labs(x="Probability", y="Total Count") + theme(plot.title = element_text(color="#666666", face="bold", size=16, hjust=0)) + theme(axis.title = element_text(color="#666666", face="bold", size=11)) + scale_fill_discrete(name="Application Status")
AIU_H <- ggplot(Multiple_Trained_Score_2copy, aes(x=AIU.Probability, fill=A_S_Label)) + geom_histogram(position="identity", alpha=0.4, bins = 100) + scale_y_log10() + ggtitle("AIU University") + labs(x="Probability", y="Total Count") + theme(plot.title = element_text(color="#666666", face="bold", size=16, hjust=0)) + theme(axis.title = element_text(color="#666666", face="bold", size=11)) + scale_fill_discrete(name="Application Status")
Argosy_H <- ggplot(Multiple_Trained_Score_2copy, aes(x=Argosy.Probability, fill=A_S_Label)) + geom_histogram(position="identity", alpha=0.4, bins = 100) + scale_y_log10() + ggtitle("Argosy University") + labs(x="Probability", y="Total Count") + theme(plot.title = element_text(color="#666666", face="bold", size=16, hjust=0)) + theme(axis.title = element_text(color="#666666", face="bold", size=11)) + scale_fill_discrete(name="Application Status")
CTU_H <- ggplot(Multiple_Trained_Score_2copy, aes(x=CTU.Probability, fill=A_S_Label)) + geom_histogram(position="identity", alpha=0.4, bins = 100) + scale_y_log10() + ggtitle("CTU") + labs(x="Probability", y="Total Count") + theme(plot.title = element_text(color="#666666", face="bold", size=16, hjust=0)) + theme(axis.title = element_text(color="#666666", face="bold", size=11)) + scale_fill_discrete(name="Application Status")
Everest_H <- ggplot(Multiple_Trained_Score_2copy, aes(x=Everest.Probability, fill=A_S_Label)) + geom_histogram(position="identity", alpha=0.4, bins = 100) + scale_y_log10() + ggtitle("Everest University") + labs(x="Probability", y="Total Count") + theme(plot.title = element_text(color="#666666", face="bold", size=16, hjust=0)) + theme(axis.title = element_text(color="#666666", face="bold", size=11)) + scale_fill_discrete(name="Application Status")
NorthCentral_H <- ggplot(Multiple_Trained_Score_2copy, aes(x=NorthCentral.Prob, fill=A_S_Label)) + geom_histogram(position="identity", alpha=0.4, bins = 100) + scale_y_log10() + ggtitle("North Central University") + labs(x="Probability", y="Total Count") + theme(plot.title = element_text(color="#666666", face="bold", size=16, hjust=0)) + theme(axis.title = element_text(color="#666666", face="bold", size=11)) + scale_fill_discrete(name="Application Status")
UltimateMedical_H <- ggplot(Multiple_Trained_Score_2copy, aes(x=Ultimate.Medical.Probability, fill=A_S_Label)) + geom_histogram(position="identity", alpha=0.4, bins = 100) + scale_y_log10() + ggtitle("Ultimate Medial") + labs(x="Probability", y="Total Count") + theme(plot.title = element_text(color="#666666", face="bold", size=16, hjust=0)) + theme(axis.title = element_text(color="#666666", face="bold", size=11)) + scale_fill_discrete(name="Application Status")
GrandCanyon_H <- ggplot(Multiple_Trained_Score_2copy, aes(x=GrandCanyon.Probability, fill=A_S_Label)) + geom_histogram(position="identity", alpha=0.4, bins = 100) + scale_y_log10() + ggtitle("Grand Canyon University") + labs(x="Probability", y="Total Count") + theme(plot.title = element_text(color="#666666", face="bold", size=16, hjust=0)) + theme(axis.title = element_text(color="#666666", face="bold", size=11)) + scale_fill_discrete(name="Application Status")
ColoradoChristian_H <- ggplot(Multiple_Trained_Score_2copy, aes(x=Col.Christian.Probability, fill=A_S_Label)) + geom_histogram(position="identity", alpha=0.4, bins = 100) + scale_y_log10() + ggtitle("Colorado Christian University") + labs(x="Probability", y="Total Count") + theme(plot.title = element_text(color="#666666", face="bold", size=16, hjust=0)) + theme(axis.title = element_text(color="#666666", face="bold", size=11)) + scale_fill_discrete(name="Application Status")
South_H <- ggplot(Multiple_Trained_Score_2copy, aes(x=South.Probability, fill=A_S_Label)) + geom_histogram(position="identity", alpha=0.4, bins = 100) + scale_y_log10() + ggtitle("South University") + labs(x="Probability", y="Total Count") + theme(plot.title = element_text(color="#666666", face="bold", size=16, hjust=0)) + theme(axis.title = element_text(color="#666666", face="bold", size=11)) + scale_fill_discrete(name="Application Status")
#######
#######
### Call grid extra package
require(gridExtra)
## Plot historagrams in grid 5 rows by 2 columns
grid.arrange(Ashford_H, AIU_H, Argosy_H, CTU_H, Everest_H, NorthCentral_H, UltimateMedical_H, GrandCanyon_H, ColoradoChristian_H, South_H, ncol=2)

